name: Auto Deploy to Google Apps Script

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Format and lint code
      run: |
        npm run format
        npm run lint:fix
    
    - name: Setup CLASP credentials
      env:
        CLASP_CREDENTIALS: ${{ secrets.CLASP_CREDENTIALS }}
        SCRIPT_ID: ${{ secrets.SCRIPT_ID }}
      run: |
        echo "$CLASP_CREDENTIALS" > ~/.clasprc.json
        echo '{"scriptId":"'$SCRIPT_ID'","rootDir":"./src"}' > .clasp.json
    
    - name: Push to Google Apps Script
      run: |
        npx @google/clasp push --force
        echo "Code successfully deployed to Google Apps Script!"
    
    - name: Deploy if main branch
      if: github.ref == 'refs/heads/main'
      run: |
        npx @google/clasp deploy --description "Auto deploy from GitHub Actions - $(date)"